FROM node:20-alpine
WORKDIR /ui
COPY package.json pnpm-lock.yaml* tsconfig.json vite.config.ts index.html /ui/
COPY src /ui/src
RUN corepack enable && pnpm i
EXPOSE 5173
CMD ["pnpm", "dev", "--host", "0.0.0.0"]
